import OsCodeBlock from '../components/OsCodeBlock';
import OsResources from '../components/OsResources';
import OsQuiz from '../components/OsQuiz';
import OsInterviewQuestion from '../components/OsInterviewQuestion';
import { MemoryViz } from '../components/OsVisualization';

export default function OsMemoryManagement() {
    return (
        <div className="module-page animate-fade-in">
            <div className="module-header">
                <span className="module-badge">MODULE 04</span>
                <h1>Memory <span className="glow-text">Management</span></h1>
                <p className="module-subtitle">Contiguous allocation, paging, segmentation, virtual memory, and page replacement.</p>
            </div>

            {/* 4.1 */}
            <section className="module-section">
                <h2>4.1  -  Memory Hierarchy & Basics</h2>
                <p>
                    Modern systems use a memory hierarchy balancing speed, size, and cost:
                </p>
                <ul>
                    <li><strong>CPU Registers</strong>  -  Fastest (~0.25 ns), smallest (hundreds of bytes), built into CPU</li>
                    <li><strong>L1 Cache</strong>  -  ~1 ns, 32 - 64 KB per core, SRAM</li>
                    <li><strong>L2 Cache</strong>  -  ~4 ns, 256 KB - 1 MB per core, SRAM</li>
                    <li><strong>L3 Cache</strong>  -  ~10 ns, 4 - 64 MB shared across cores, SRAM</li>
                    <li><strong>Main Memory (RAM)</strong>  -  ~100 ns, 4 - 128 GB, DRAM, volatile</li>
                    <li><strong>SSD Storage</strong>  -  ~100 μs, 256 GB - 8 TB, flash, non-volatile</li>
                    <li><strong>HDD Storage</strong>  -  ~10 ms, 1 - 20 TB, magnetic, non-volatile</li>
                </ul>
                <p>
                    The OS manages the interplay between these levels, using caching and virtual memory to give the
                    illusion of large, fast memory at low cost.
                </p>
            </section>

            {/* 4.2 */}
            <section className="module-section">
                <h2>4.2  -  Address Binding</h2>
                <p>
                    Programs must be loaded into memory before execution. The binding of instructions and data to
                    memory addresses can happen at three stages:
                </p>
                <ul>
                    <li><strong>Compile Time</strong>  -  Absolute addresses generated at compile time. The process must load at the specified address. Cannot be relocated. Example: embedded systems, MS-DOS .COM files.</li>
                    <li><strong>Load Time</strong>  -  Compiler generates relocatable code. The loader assigns final addresses when the program is loaded into memory. Process can load at any free address.</li>
                    <li><strong>Execution Time</strong>  -  Binding is deferred until runtime. Requires hardware support (MMU). Process can be moved during execution (swapping). <strong>Most modern systems use this.</strong></li>
                </ul>
                <h3>Logical vs Physical Addresses</h3>
                <p>
                    <strong>Logical (Virtual) Address</strong>  -  Generated by the CPU during execution. What the program "sees."
                    <strong> Physical Address</strong>  -  Actual location in RAM. What the memory hardware uses.
                    The <strong>MMU (Memory Management Unit)</strong> translates logical  to  physical at runtime. The set of
                    all logical addresses is the <strong>logical address space</strong>; all physical addresses form the
                    <strong> physical address space</strong>. Programs never see physical addresses.
                </p>
            </section>

            {/* 4.3 */}
            <section className="module-section">
                <h2>4.3  -  Contiguous Memory Allocation</h2>
                <p>
                    Each process is allocated a single contiguous section of memory. Uses <strong>base register</strong>
                    (starting address) and <strong>limit register</strong> (size). MMU checks: base ≤ address &lt; base + limit.
                </p>
                <h3>Allocation Strategies</h3>
                <ul>
                    <li><strong>First-Fit</strong>  -  Allocate the first hole big enough. Fastest. Tends to fragment the beginning of memory.</li>
                    <li><strong>Best-Fit</strong>  -  Allocate the smallest hole that is big enough. Produces smallest leftover fragments but requires searching entire list.</li>
                    <li><strong>Worst-Fit</strong>  -  Allocate the largest hole. Produces largest leftover (potentially more useful). Worst performance in practice.</li>
                    <li><strong>Next-Fit</strong>  -  Like first-fit but starts searching from where the last allocation ended. More uniform memory usage.</li>
                </ul>
                <h3>Fragmentation</h3>
                <ul>
                    <li><strong>External Fragmentation</strong>  -  Total free memory is sufficient, but it's scattered in non-contiguous small holes. Solved by: compaction (expensive, requires relocation), or paging.</li>
                    <li><strong>Internal Fragmentation</strong>  -  Allocated memory is slightly larger than requested (due to fixed block sizes). The excess space within the allocated block is wasted.</li>
                </ul>
            </section>

            {/* 4.4 */}
            <section className="module-section">
                <h2>4.4  -  Paging</h2>
                <p>
                    Paging eliminates external fragmentation by dividing memory into fixed-size chunks:
                </p>
                <ul>
                    <li><strong>Pages</strong>  -  Fixed-size blocks of the logical address space (typically 4 KB)</li>
                    <li><strong>Frames</strong>  -  Same-size blocks of physical memory</li>
                    <li><strong>Page Table</strong>  -  Per-process mapping: page number  to  frame number</li>
                </ul>
                <h3>Address Translation</h3>
                <p>
                    A logical address is split into: <strong>page number (p)</strong> (index into page table) and
                    <strong> page offset (d)</strong> (offset within the page). Physical address = frame_number × page_size + d.
                    With 4 KB pages and a 32-bit address: 20 bits for page number (1M pages), 12 bits for offset (4096 bytes).
                </p>
                <h3>Page Table Implementation</h3>
                <ul>
                    <li><strong>Simple Page Table</strong>  -  Array indexed by page number. Fast but wastes memory for sparse address spaces.</li>
                    <li><strong>Multi-Level Page Tables</strong>  -  Hierarchical: outer page table  to  inner page tables. Only allocate inner tables for used pages. x86 uses 2-level (32-bit) or 4-level (64-bit) paging.</li>
                    <li><strong>Inverted Page Table</strong>  -  One entry per physical frame (not per logical page). Smaller but requires hash lookup. Used in IBM PowerPC.</li>
                    <li><strong>Hashed Page Table</strong>  -  Hash the virtual page number. Good for sparse 64-bit address spaces.</li>
                </ul>
                <h3>Page Table Entries (PTE)</h3>
                <p>Each entry contains:</p>
                <ul>
                    <li><strong>Frame Number</strong>  -  Physical frame where the page resides</li>
                    <li><strong>Valid/Present Bit</strong>  -  1 if page is in memory, 0 if on disk</li>
                    <li><strong>Protection Bits</strong>  -  Read/Write/Execute permissions</li>
                    <li><strong>Dirty Bit</strong>  -  1 if page has been modified (must be written to disk before eviction)</li>
                    <li><strong>Referenced/Accessed Bit</strong>  -  1 if page has been read or written recently (used by page replacement)</li>
                </ul>
                <h3>TLB (Translation Lookaside Buffer)</h3>
                <p>
                    The TLB is a small, fast, fully associative hardware cache for page table entries. Without TLB,
                    every memory access requires two accesses (one to page table, one to the actual data). With TLB,
                    the page-to-frame mapping is cached for frequently accessed pages.
                </p>
                <ul>
                    <li><strong>TLB Hit</strong>  -  Page mapping found in TLB. Translation in ~1 CPU cycle.</li>
                    <li><strong>TLB Miss</strong>  -  Must consult the page table in memory (~100 ns). The mapping is then cached in TLB.</li>
                    <li><strong>TLB Flush</strong>  -  On context switch, TLB entries become invalid (different process). Can use ASIDs (Address Space Identifiers) to tag entries and avoid full flushes.</li>
                    <li><strong>Hit Ratio</strong>  -  Typical: 98 - 99%. Even small TLBs (64 - 1024 entries) work due to spatial and temporal locality.</li>
                </ul>
            </section>

            <MemoryViz />

            {/* 4.5 */}
            <section className="module-section">
                <h2>4.5  -  Segmentation</h2>
                <p>
                    Segmentation divides memory according to the user's logical view  -  each segment represents a
                    logical unit: code, data, stack, heap. Unlike paging (fixed-size), segments have <strong>variable sizes</strong>.
                </p>
                <ul>
                    <li>Logical address = (segment number, offset)</li>
                    <li>Segment table maps: segment  to  (base, limit)</li>
                    <li>If offset &lt; limit, physical address = base + offset</li>
                    <li><strong>Advantage:</strong> Matches programmer's view of memory</li>
                    <li><strong>Disadvantage:</strong> External fragmentation (variable-size segments)</li>
                </ul>
                <h3>Segmented Paging</h3>
                <p>
                    Combines both: segments are paged. Each segment has its own page table. Used by x86 architecture
                    (though modern 64-bit OS like Linux use flat segmentation with just paging). Eliminates external
                    fragmentation while preserving the logical segment view.
                </p>
            </section>

            {/* 4.6 */}
            <section className="module-section">
                <h2>4.6  -  Virtual Memory</h2>
                <p>
                    Virtual memory allows execution of processes larger than physical memory. Only the needed portions
                    of a process reside in memory; the rest stays on disk. Provides the illusion of a very large address space.
                </p>
                <h3>Demand Paging</h3>
                <p>
                    Pages are loaded into memory only when accessed (lazy loading). The process starts with no pages in
                    memory. Each access to a non-resident page triggers a <strong>page fault</strong>.
                </p>
                <h3>Page Fault Handling</h3>
                <ol>
                    <li>CPU generates a page fault trap when accessing page with valid bit = 0</li>
                    <li>OS verifies the access is legal (check the process's address space)</li>
                    <li>Find a free frame in physical memory (or use page replacement if no free frame)</li>
                    <li>Schedule a disk I/O to read the page from disk (swap space or file) into the frame</li>
                    <li>Update the page table entry: set frame number, set valid bit = 1</li>
                    <li>Restart the instruction that caused the page fault</li>
                </ol>
                <p>
                    <strong>Effective Access Time</strong> = (1 - p) × memory_access_time + p × page_fault_time,
                    where p is the page fault rate. If memory access = 100 ns and page fault = 8 ms, even a 0.1%
                    fault rate slows access by 80×.
                </p>
                <h3>Copy-on-Write (COW)</h3>
                <p>
                    When <code>fork()</code> is called, instead of copying all pages, both parent and child share the same
                    pages marked as read-only. When either process writes to a page, a page fault occurs, and only then
                    is that specific page copied. This is efficient because many forked children call <code>exec()</code>
                    immediately, never modifying the parent's pages.
                </p>
                <h3>Memory-Mapped Files</h3>
                <p>
                    Map a file directly into the process's address space. Reading/writing the mapped memory region
                    reads/writes the file. The OS handles paging the file contents in and out of memory. More efficient
                    than explicit read/write system calls for random access patterns. Used by: shared libraries (.so/.dll),
                    database systems, and <code>mmap()</code> system call.
                </p>
            </section>

            {/* 4.7 */}
            <section className="module-section">
                <h2>4.7  -  Page Replacement Algorithms</h2>
                <p>
                    When a page fault occurs and no free frames are available, the OS must choose a <strong>victim page</strong>
                    to evict. If the victim has been modified (dirty bit = 1), it must be written back to disk first.
                </p>
                <h3>FIFO (First-In, First-Out)</h3>
                <p>
                    Replace the oldest page in memory. Simple to implement (just a queue). <strong>Suffers from
                        Belady's anomaly</strong>  -  more frames can lead to more page faults in certain access patterns.
                </p>
                <h3>Optimal (OPT / MIN)</h3>
                <p>
                    Replace the page that will not be used for the longest time in the future. <strong>Lowest possible
                        page fault rate</strong>. Cannot be implemented in practice (requires future knowledge). Used as a
                    theoretical benchmark to compare against other algorithms.
                </p>
                <h3>LRU (Least Recently Used)</h3>
                <p>
                    Replace the page that has not been used for the longest time (past behavior predicts future).
                    Good approximation of OPT. Does not suffer from Belady's anomaly. <strong>Implementation challenges:</strong>
                    exact LRU requires timestamp or stack tracking for every memory access (expensive). Approximations:
                    additional reference bits, second-chance (clock) algorithm.
                </p>
                <h3>Clock Algorithm (Second Chance)</h3>
                <p>
                    Approximates LRU using a circular buffer with a "clock hand." Each page has a reference bit (set on access).
                    When needing a victim: if reference bit = 1, clear it and advance (give a second chance). If reference
                    bit = 0, select it as victim. Efficient and commonly used in real systems.
                </p>
                <h3>LFU (Least Frequently Used)</h3>
                <p>
                    Replace the page with the smallest access count. Problem: a page heavily used early but no longer needed
                    stays in memory. Solution: decay/aging of counters. Used less commonly than LRU variants.
                </p>
                <h3>MFU (Most Frequently Used)</h3>
                <p>
                    Replace the page with the highest access count (reasoning: pages with low count were just
                    brought in and will likely be used again). Rarely used in practice.
                </p>
                <OsCodeBlock
                    title="memory_management"
                    codes={{
                        c: `#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <unistd.h>

int main() {
    // ---- Dynamic allocation (heap) ----
    int *arr = (int*)malloc(10 * sizeof(int));
    for (int i = 0; i < 10; i++) arr[i] = i * 10;

    // Resize (realloc may move the block)
    arr = (int*)realloc(arr, 20 * sizeof(int));
    for (int i = 10; i < 20; i++) arr[i] = i * 10;

    printf("arr[15] = %d\\n", arr[15]);
    free(arr);

    // ---- Memory-mapped file ----
    const char *filename = "mmap_test.txt";
    int fd = open(filename, O_RDWR | O_CREAT | O_TRUNC, 0644);
    const char *data = "Hello, memory-mapped world!\\n";
    write(fd, data, strlen(data));

    // Map the file into memory
    char *mapped = mmap(NULL, 4096, PROT_READ | PROT_WRITE,
                        MAP_SHARED, fd, 0);
    if (mapped == MAP_FAILED) {
        perror("mmap");
        return 1;
    }

    printf("Mapped content: %s", mapped);

    // Modify through memory (changes the file!)
    mapped[0] = 'J';
    msync(mapped, 4096, MS_SYNC);
    printf("Modified content: %s", mapped);

    munmap(mapped, 4096);
    close(fd);
    unlink(filename);

    return 0;
}`,
                        python: `import sys
import mmap
import os
import ctypes

# ---- Memory info ----
a = [1, 2, 3, 4, 5]
print(f"List size: {sys.getsizeof(a)} bytes")
print(f"Ref count: {sys.getrefcount(a)}")
print(f"Address  : {hex(id(a))}")

# ---- Memory-mapped file ----
filename = "mmap_test.txt"
with open(filename, "w") as f:
    f.write("Hello, memory-mapped world!\\n")

with open(filename, "r+b") as f:
    mm = mmap.mmap(f.fileno(), 0)
    print(f"Mapped content: {mm.readline().decode()}")

    # Modify through memory
    mm.seek(0)
    mm.write(b"J")
    mm.flush()

    mm.seek(0)
    print(f"Modified: {mm.readline().decode()}")
    mm.close()

os.unlink(filename)

# ---- Process memory info ----
import resource
usage = resource.getrusage(resource.RUSAGE_SELF)
print(f"Max RSS: {usage.ru_maxrss} KB")
print(f"Page faults (major): {usage.ru_majflt}")
print(f"Page faults (minor): {usage.ru_minflt}")`,
                        java: `import java.io.*;
import java.nio.*;
import java.nio.channels.*;
import java.nio.file.*;

public class MemoryDemo {
    public static void main(String[] args) throws Exception {
        Runtime rt = Runtime.getRuntime();
        System.out.println("Max Memory  : " + rt.maxMemory() / (1024 * 1024) + " MB");
        System.out.println("Total Memory: " + rt.totalMemory() / (1024 * 1024) + " MB");
        System.out.println("Free Memory : " + rt.freeMemory() / (1024 * 1024) + " MB");

        // ---- Allocate memory ----
        byte[] data = new byte[50 * 1024 * 1024]; // 50 MB
        System.out.println("\\nAfter 50MB allocation:");
        System.out.println("Free Memory : " + rt.freeMemory() / (1024 * 1024) + " MB");
        data = null;
        System.gc();

        // ---- Memory-mapped file ----
        Path path = Path.of("mmap_test.txt");
        Files.writeString(path, "Hello, memory-mapped world!\\n");

        try (FileChannel channel = FileChannel.open(path,
                StandardOpenOption.READ, StandardOpenOption.WRITE)) {

            MappedByteBuffer mapped = channel.map(
                FileChannel.MapMode.READ_WRITE, 0, channel.size());

            // Read from mapped memory
            byte[] buf = new byte[(int)channel.size()];
            mapped.get(buf);
            System.out.println("Mapped: " + new String(buf).trim());

            // Modify through memory
            mapped.position(0);
            mapped.put((byte)'J');
            mapped.force(); // Sync to disk
        }

        System.out.println("Modified: " + Files.readString(path).trim());
        Files.delete(path);

        // ---- Direct ByteBuffer (off-heap) ----
        ByteBuffer direct = ByteBuffer.allocateDirect(1024);
        direct.putInt(42);
        direct.flip();
        System.out.println("Direct buffer value: " + direct.getInt());
    }
}`,
                    }}
                />
            </section>

            {/* 4.8 */}
            <section className="module-section">
                <h2>4.8  -  Thrashing & Working Set</h2>
                <h3>Thrashing</h3>
                <p>
                    Thrashing occurs when a process spends more time paging (swapping pages in and out) than
                    executing useful instructions. It happens when the system is overcommitted  -  too many processes
                    competing for too little physical memory. The page fault rate skyrockets, CPU utilization
                    drops (the OS keeps scheduling more processes thinking the CPU is idle), creating a vicious cycle.
                </p>
                <h3>Working Set Model</h3>
                <p>
                    The <strong>working set</strong> W(t, Δ) is the set of pages referenced in the last Δ time units.
                    If the working set of a process fits in its allocated frames, it runs well. If not, it thrashes.
                    The OS should ensure Σ(working set sizes) ≤ total physical frames. If the total exceeds available
                    memory, the OS should <strong>suspend (swap out)</strong> one or more processes.
                </p>
                <h3>Page Fault Frequency (PFF)</h3>
                <p>
                    A more direct approach: monitor each process's page fault rate. If the rate exceeds an
                    <strong> upper threshold</strong>, allocate more frames. If it falls below a <strong>lower threshold</strong>,
                    reduce frames. This dynamically adjusts allocation based on actual behavior.
                </p>
            </section>

            {/* 4.9 */}
            <section className="module-section">
                <h2>4.9  -  Swapping</h2>
                <p>
                    Swapping is the process of moving an entire process's memory between main memory and disk (swap space).
                    Used by the medium-term scheduler to reduce multiprogramming degree during high memory pressure.
                </p>
                <ul>
                    <li><strong>Swap Out</strong>  -  Write process's pages to swap space on disk</li>
                    <li><strong>Swap In</strong>  -  Read process's pages back from swap space to memory</li>
                    <li><strong>Swap Space</strong>  -  Dedicated disk partition or file for swapped pages (faster than regular filesystem)</li>
                    <li><strong>Modern systems</strong> prefer page-level swapping (demand paging) over process-level swapping</li>
                </ul>
            </section>

            <OsQuiz
                title="Module 4  -  Comprehensive Check"
                questions={[
                    {
                        question: 'What does TLB stand for?',
                        options: ['Thread Local Buffer', 'Translation Lookaside Buffer', 'Temporary Load Block', 'Table Lookup Base'],
                        answer: 1,
                    },
                    {
                        question: 'Which page replacement suffers from Belady\'s anomaly?',
                        options: ['LRU', 'Optimal', 'FIFO', 'Clock'],
                        answer: 2,
                        explanation: 'With FIFO, more frames can paradoxically lead to more page faults.',
                    },
                    {
                        question: 'What is thrashing?',
                        options: ['Fast disk access', 'Excessive paging that degrades performance', 'A type of deadlock', 'CPU overclocking'],
                        answer: 1,
                    },
                    {
                        question: 'In a 32-bit system with 4 KB pages, how many page table entries are needed?',
                        options: ['4096', '1024', '1,048,576 (2^20)', '65,536'],
                        answer: 2,
                        explanation: '32 bit address / 12 bit offset (4KB) = 20 bits for page number = 2^20 = ~1 million entries.',
                    },
                    {
                        question: 'Which allocation strategy produces the smallest leftover?',
                        options: ['First-Fit', 'Best-Fit', 'Worst-Fit', 'Next-Fit'],
                        answer: 1,
                        explanation: 'Best-Fit finds the smallest hole that fits, producing the smallest leftover fragment.',
                    },
                ]}
            />

            <OsResources topicId="memory" />

            <section className="module-section">
                <h2>Interview Corner</h2>
                <OsInterviewQuestion
                    question="What is the difference between paging and segmentation?"
                    answer="Paging divides memory into fixed-size pages/frames  -  transparent to the programmer, eliminates external fragmentation, but causes internal fragmentation. Segmentation divides memory into variable-size logical segments (code, data, stack)  -  matches the programmer's logical view but causes external fragmentation. Modern systems use segmented paging (segments are paged) to get the benefits of both  -  logical organization of segments with paging's elimination of external fragmentation."
                />
                <OsInterviewQuestion
                    question="Explain demand paging and its performance impact."
                    answer="Demand paging loads pages into memory only when they are accessed (page fault), not in advance. Benefits: less memory usage, faster process startup, enables processes larger than physical memory. Performance: if memory access = 100 ns and page fault service = 8 ms, with 0.1% fault rate, effective access time = 0.999 × 100 ns + 0.001 × 8 ms ≈ 8.1 μs  -  an 80× slowdown. That's why low page fault rates (<0.01%) are critical."
                />
                <OsInterviewQuestion
                    question="Explain copy-on-write. Why is it important for fork()?"
                    answer="Copy-on-Write (COW) defers the copying of memory pages during fork(). Instead of duplicating all parent pages, both parent and child share the same physical frames, marked as read-only. When either process writes to a page, a page fault occurs, the OS copies just that page to a new frame, and both processes continue independently. This is important because: 1) fork() alone would be prohibitively expensive for large processes, 2) Many forked children call exec() immediately, replacing their entire address space  -  COW avoids copying memory that would be discarded anyway."
                />
                <OsInterviewQuestion
                    question="Compare LRU and FIFO page replacement. Can more frames cause more page faults?"
                    answer="LRU replaces the least recently used page (uses past behavior to predict future). FIFO replaces the oldest page (regardless of recent usage). LRU generally performs better and does NOT suffer from Belady's anomaly  -  more frames always means ≤ page faults. FIFO DOES suffer from Belady's anomaly: for the reference string 1,2,3,4,1,2,5,1,2,3,4,5, using 3 frames gives 9 faults but 4 frames gives 10 faults! This counterintuitive result makes FIFO less reliable despite being simpler."
                />
            </section>
        </div>
    );
}
