services:
  - type: web
    name: tech-in-my-style-python-studio
    env: python
    rootDir: server/python-studio
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    region: virginia
    plan: free
    envVars:
      - key: USE_DOCKER
        value: "false"
      - key: EXECUTION_TIMEOUT
        value: "30"
      - key: PYTHONUNBUFFERED
        value: "1"
